baseURL: 'https://grealish.co.uk/'
languageCode: en-GB
title: Ashley Grealish
theme: hugo-sustain
permalinks:
  post: '/:year/:month/:day/:slug'
params:
  avatar: /img/headshot.jpg
  author: Ashley Grealish
  description: About Ashley Grealish - Enginering Leader using tech for good
  custom_css:
    - main.css
  custom_js: []
  social:
    Github: a-grealish
    LinkedIn: agrealish
markup:
  goldmark:
    renderer:
      unsafe: true
menu:
  main:
    - name: Work
      identifier: about
      weight: 100
      url: /about/
    - name: Talks
      identifier: media
      weight: 200
      url: /media/
    - name: Side Projects
      identifier: projects
      weight: 300
      url: /projects/
    - name: Blog
      identifier: blog
      weight: 400
      url: /blog/
    - name: contact
      weight: 500
      identifier: contact
      url: /contact/
