baseURL = "https://grealish.co.uk/"
languageCode = "en-GB"
title = "Ashley Grealish"
# Enable comments by entering your Disqus shortname

# TODO - what is disqus? Commenting?
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "/img/headshot.jpg"
  author = "Ashley Grealish"
  description = "About Ashley Grealish - Enginering Leader using tech for good"

  # Custom assets can be linked with their paths relative to static/
  custom_css = ["main.css"]
  custom_js  = []

[params.social]
  Github        = "a-grealish"
  # Email         = "email@example.com"
  # Twitter       = "username"
  LinkedIn      = "agrealish"
  # Stackoverflow = "username"
  # Medium        = "username"
  # Telegram      = "username"
  # RSS           = "/blog/index.xml"

[markup.goldmark.renderer]
  unsafe = true

## Main Menu
[[menu.main]]
  name = "My Work"
  identifier = "about"
  weight = 100
  url = "/about/"
[[menu.main]]
  name = "Side Projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "Aviation Blog"
  identifier = "aviation"
  weight = 300
  url = "/aviation/"
[[menu.main]]
  name = "blog"
  weight = 400
  identifier = "blog"
  url = "https://blog.grealish.co.uk"
