name: Push to GitHub Pages on push to main

on:
  push:
    branches:
      - main

env:
  # Override the default GITHUB_TOKEN to allow deploy to another repo
  GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v1
        with:
          # Fetch Hugo themes
          submodules: true  
 
      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.92.2
          TARGET_REPO: a-grealish/a-grealish.github.io
          TARGET_BRANCH: main
          # Custom args not needed 
          # HUGO_ARGS: '-t hugo-sustain' 
          CNAME: grealish.co.uk